version: '3'
services:
  emscripten:
    container_name: emscripten-compiler
    image: rnix/emsdk
    volumes:
      - ./emscripten-cpp-source:/src
    command: em++ -std=c++1z --bind main.cpp -o index.html
  web:
    container_name: webapp-frontend
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./emscripten-cpp-source:/go/src/github.com/dirkarnez/golang-hello-world/emscripten-cpp-source
    depends_on:
      - emscripten
