version: '3'
services:
  emscripten:
    container_name: emscripten-compiler
    image: rnix/emsdk
    working_dir: ./emscripten-cpp-source
    command: em++ -std=c++1z --bind main.cpp -o ../public/index.html
  web:
    container_name: webapp-frontend
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - emscripten
